name: Generate Datas

on:
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Generate Snake Animation
      - name: Generate snake
        uses: Platane/snk@master
        with:
          github_user_name: Archit-Jain05
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push to output branch
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
